// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastFind
Rcpp::DataFrame fastFind(IntegerVector PrePro_indexFilter, NumericVector Original_times, NumericVector Original_prices);
RcppExport SEXP _ChartPatterns_fastFind(SEXP PrePro_indexFilterSEXP, SEXP Original_timesSEXP, SEXP Original_pricesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type PrePro_indexFilter(PrePro_indexFilterSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Original_times(Original_timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Original_prices(Original_pricesSEXP);
    rcpp_result_gen = Rcpp::wrap(fastFind(PrePro_indexFilter, Original_times, Original_prices));
    return rcpp_result_gen;
END_RCPP
}
// fastFind_chaosRegin
Rcpp::DataFrame fastFind_chaosRegin(IntegerVector PrePro_indexFilter, NumericVector Original_times, NumericVector Original_prices);
RcppExport SEXP _ChartPatterns_fastFind_chaosRegin(SEXP PrePro_indexFilterSEXP, SEXP Original_timesSEXP, SEXP Original_pricesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type PrePro_indexFilter(PrePro_indexFilterSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Original_times(Original_timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Original_prices(Original_pricesSEXP);
    rcpp_result_gen = Rcpp::wrap(fastFind_chaosRegin(PrePro_indexFilter, Original_times, Original_prices));
    return rcpp_result_gen;
END_RCPP
}
// getSlope
double getSlope(double x1, double x2, double y1, double y2);
RcppExport SEXP _ChartPatterns_getSlope(SEXP x1SEXP, SEXP x2SEXP, SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< double >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< double >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(getSlope(x1, x2, y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// linearInterpolation
double linearInterpolation(double x1, double x2, double y1, double y2, double atPosition);
RcppExport SEXP _ChartPatterns_linearInterpolation(SEXP x1SEXP, SEXP x2SEXP, SEXP y1SEXP, SEXP y2SEXP, SEXP atPositionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< double >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< double >::type y2(y2SEXP);
    Rcpp::traits::input_parameter< double >::type atPosition(atPositionSEXP);
    rcpp_result_gen = Rcpp::wrap(linearInterpolation(x1, x2, y1, y2, atPosition));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ChartPatterns_fastFind", (DL_FUNC) &_ChartPatterns_fastFind, 3},
    {"_ChartPatterns_fastFind_chaosRegin", (DL_FUNC) &_ChartPatterns_fastFind_chaosRegin, 3},
    {"_ChartPatterns_getSlope", (DL_FUNC) &_ChartPatterns_getSlope, 4},
    {"_ChartPatterns_linearInterpolation", (DL_FUNC) &_ChartPatterns_linearInterpolation, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ChartPatterns(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
